package org.opentopo.app.ui

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.Verified
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import org.opentopo.app.ui.theme.CoordinateFont
import org.opentopo.app.ui.theme.LocalSurveyColors
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Result of comparing measured GNSS position against a known trig point.
 */
data class VerificationResult(
    val pointName: String,
    // Published (known) coordinates — EGSA87
    val publishedE: Double,
    val publishedN: Double,
    val publishedH: Double?,
    // Measured coordinates — EGSA87
    val measuredE: Double,
    val measuredN: Double,
    val measuredH: Double?,
    // Residuals
    val deltaE: Double,
    val deltaN: Double,
    val deltaH: Double?,
    val horizontalResidual: Double,
    // GNSS quality at time of measurement
    val fixQuality: Int,
    val horizontalAccuracy: Double?,
    val numSatellites: Int,
    val timestamp: Long = System.currentTimeMillis(),
) {
    val fixLabel: String
        get() = when (fixQuality) {
            4 -> "RTK Fix"
            5 -> "RTK Float"
            2 -> "DGPS"
            1 -> "GPS"
            else -> "No fix"
        }

    fun toShareText(): String = buildString {
        appendLine("=== Trig Point Verification Report ===")
        appendLine("Point: $pointName")
        appendLine("Date: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(Date(timestamp))}")
        appendLine()
        appendLine("Published EGSA87:")
        appendLine("  E: ${"%.3f".format(publishedE)} m")
        appendLine("  N: ${"%.3f".format(publishedN)} m")
        publishedH?.let { appendLine("  H: ${"%.3f".format(it)} m") }
        appendLine()
        appendLine("Measured EGSA87:")
        appendLine("  E: ${"%.3f".format(measuredE)} m")
        appendLine("  N: ${"%.3f".format(measuredN)} m")
        measuredH?.let { appendLine("  H: ${"%.3f".format(it)} m") }
        appendLine()
        appendLine("Residuals:")
        appendLine("  \u0394E: ${"%.3f".format(deltaE)} m")
        appendLine("  \u0394N: ${"%.3f".format(deltaN)} m")
        deltaH?.let { appendLine("  \u0394H: ${"%.3f".format(it)} m") }
        appendLine("  Horizontal: ${"%.3f".format(horizontalResidual)} m")
        appendLine()
        appendLine("GNSS Quality: $fixLabel")
        horizontalAccuracy?.let { appendLine("Accuracy: \u00B1${"%.3f".format(it)} m") }
        appendLine("Satellites: $numSatellites")
        appendLine()
        appendLine("Generated by OpenTopo")
    }
}

@Composable
fun VerificationReportDialog(
    result: VerificationResult,
    onDismiss: () -> Unit,
    onShare: (String) -> Unit,
) {
    val surveyColors = LocalSurveyColors.current

    androidx.compose.material3.AlertDialog(
        onDismissRequest = onDismiss,
        icon = {
            Icon(
                Icons.Outlined.Verified,
                contentDescription = null,
                tint = if (result.horizontalResidual < 0.05) MaterialTheme.colorScheme.primary
                else MaterialTheme.colorScheme.error,
            )
        },
        title = {
            Text("Verification: ${result.pointName}")
        },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                // Residuals (the key info)
                Text(
                    "Residuals",
                    style = MaterialTheme.typography.titleSmall,
                    color = MaterialTheme.colorScheme.primary,
                )
                ResidualRow("\u0394E", result.deltaE)
                ResidualRow("\u0394N", result.deltaN)
                result.deltaH?.let { ResidualRow("\u0394H", it) }

                Spacer(Modifier.height(4.dp))
                val residualColor = when {
                    result.horizontalResidual < 0.02 -> surveyColors.fixColor(4) // green
                    result.horizontalResidual < 0.05 -> surveyColors.fixColor(5) // amber
                    else -> surveyColors.fixColor(0) // red
                }
                Text(
                    "Horizontal: ${"%.3f".format(result.horizontalResidual)} m",
                    style = MaterialTheme.typography.titleMedium,
                    fontFamily = CoordinateFont,
                    fontWeight = FontWeight.Bold,
                    color = residualColor,
                )

                HorizontalDivider(Modifier.padding(vertical = 4.dp))

                // Coordinates comparison
                Text(
                    "Published",
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
                Text(
                    "E ${"%.3f".format(result.publishedE)}  N ${"%.3f".format(result.publishedN)}",
                    style = MaterialTheme.typography.bodyMedium,
                    fontFamily = CoordinateFont,
                )

                Text(
                    "Measured",
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
                Text(
                    "E ${"%.3f".format(result.measuredE)}  N ${"%.3f".format(result.measuredN)}",
                    style = MaterialTheme.typography.bodyMedium,
                    fontFamily = CoordinateFont,
                )

                HorizontalDivider(Modifier.padding(vertical = 4.dp))

                // GNSS quality
                Row(
                    Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                ) {
                    Text(
                        result.fixLabel,
                        style = MaterialTheme.typography.labelLarge,
                        color = surveyColors.fixColor(result.fixQuality),
                    )
                    result.horizontalAccuracy?.let {
                        Text(
                            "\u00B1${"%.3f".format(it)}m",
                            style = MaterialTheme.typography.labelLarge,
                            fontFamily = CoordinateFont,
                        )
                    }
                    Text(
                        "${result.numSatellites} sats",
                        style = MaterialTheme.typography.labelLarge,
                        fontFamily = CoordinateFont,
                    )
                }

                // Timestamp
                Text(
                    SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(Date(result.timestamp)),
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }
        },
        confirmButton = {
            TextButton(onClick = { onShare(result.toShareText()) }) {
                Text("Share")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Close")
            }
        },
    )
}

@Composable
private fun ResidualRow(label: String, value: Double) {
    Row(
        Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.SpaceBetween,
    ) {
        Text(
            label,
            style = MaterialTheme.typography.bodyMedium,
            fontWeight = FontWeight.Medium,
        )
        Text(
            "${"%.3f".format(value)} m",
            style = MaterialTheme.typography.bodyMedium,
            fontFamily = CoordinateFont,
            fontWeight = FontWeight.Bold,
            color = if (kotlin.math.abs(value) < 0.02)
                MaterialTheme.colorScheme.primary
            else if (kotlin.math.abs(value) < 0.05)
                MaterialTheme.colorScheme.tertiary
            else
                MaterialTheme.colorScheme.error,
        )
    }
}
