package org.opentopo.app.ui

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.size
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.AccessTime
import androidx.compose.material.icons.outlined.Verified
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import org.opentopo.app.ui.components.CoordinateBlock
import org.opentopo.app.ui.components.TonalCard
import org.opentopo.app.ui.theme.CoordinateFont
import org.opentopo.app.ui.theme.LabelOverline
import org.opentopo.app.ui.theme.LocalSurveyColors
import org.opentopo.app.ui.theme.MonoDelta
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Result of comparing measured GNSS position against a known trig point.
 */
data class VerificationResult(
    val pointName: String,
    // Published (known) coordinates — EGSA87
    val publishedE: Double,
    val publishedN: Double,
    val publishedH: Double?,
    // Measured coordinates — EGSA87
    val measuredE: Double,
    val measuredN: Double,
    val measuredH: Double?,
    // Residuals
    val deltaE: Double,
    val deltaN: Double,
    val deltaH: Double?,
    val horizontalResidual: Double,
    // GNSS quality at time of measurement
    val fixQuality: Int,
    val horizontalAccuracy: Double?,
    val numSatellites: Int,
    val timestamp: Long = System.currentTimeMillis(),
) {
    val fixLabel: String
        get() = when (fixQuality) {
            4 -> "RTK Fix"
            5 -> "RTK Float"
            2 -> "DGPS"
            1 -> "GPS"
            else -> "No fix"
        }

    fun toShareText(): String = buildString {
        appendLine("=== Trig Point Verification Report ===")
        appendLine("Point: $pointName")
        appendLine("Date: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(Date(timestamp))}")
        appendLine()
        appendLine("Published EGSA87:")
        appendLine("  E: ${"%.3f".format(publishedE)} m")
        appendLine("  N: ${"%.3f".format(publishedN)} m")
        publishedH?.let { appendLine("  H: ${"%.3f".format(it)} m") }
        appendLine()
        appendLine("Measured EGSA87:")
        appendLine("  E: ${"%.3f".format(measuredE)} m")
        appendLine("  N: ${"%.3f".format(measuredN)} m")
        measuredH?.let { appendLine("  H: ${"%.3f".format(it)} m") }
        appendLine()
        appendLine("Residuals:")
        appendLine("  \u0394E: ${"%.3f".format(deltaE)} m")
        appendLine("  \u0394N: ${"%.3f".format(deltaN)} m")
        deltaH?.let { appendLine("  \u0394H: ${"%.3f".format(it)} m") }
        appendLine("  Horizontal: ${"%.3f".format(horizontalResidual)} m")
        appendLine()
        appendLine("GNSS Quality: $fixLabel")
        horizontalAccuracy?.let { appendLine("Accuracy: \u00B1${"%.3f".format(it)} m") }
        appendLine("Satellites: $numSatellites")
        appendLine()
        appendLine("Generated by OpenTopo")
    }
}

@OptIn(androidx.compose.material3.ExperimentalMaterial3ExpressiveApi::class)
@Composable
fun VerificationReportDialog(
    result: VerificationResult,
    onDismiss: () -> Unit,
    onShare: (String) -> Unit,
) {
    val surveyColors = LocalSurveyColors.current
    val headlineColor = when {
        result.horizontalResidual < 0.02 -> surveyColors.fixColor(4) // green
        result.horizontalResidual < 0.05 -> surveyColors.fixColor(5) // amber
        else -> surveyColors.fixColor(0) // red
    }

    androidx.compose.material3.AlertDialog(
        onDismissRequest = onDismiss,
        shape = MaterialTheme.shapes.extraLarge,
        icon = {
            Icon(
                Icons.Outlined.Verified,
                contentDescription = null,
                tint = if (result.horizontalResidual < 0.05) surveyColors.fixColor(4)
                else MaterialTheme.colorScheme.error,
            )
        },
        title = {
            Text("Verification: ${result.pointName}")
        },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                // Section 1 — Headline residual (centered)
                Column(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalAlignment = Alignment.CenterHorizontally,
                ) {
                    Text(
                        "Horizontal residual",
                        style = LabelOverline,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        textAlign = TextAlign.Center,
                    )
                    Text(
                        "${"%.3f".format(result.horizontalResidual)} m",
                        style = MaterialTheme.typography.displaySmallEmphasized,
                        fontFamily = CoordinateFont,
                        color = headlineColor,
                        textAlign = TextAlign.Center,
                    )
                }

                // Section 2 — Component residuals ΔE / ΔN / ΔH
                TonalCard {
                    Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                        ResidualRow("\u0394E", result.deltaE)
                        ResidualRow("\u0394N", result.deltaN)
                        result.deltaH?.let { ResidualRow("\u0394H", it) }
                    }
                }

                // Section 3 — Published vs Measured coordinate blocks
                Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                    CoordinateBlock(
                        label = "PUBLISHED \u00B7 EGSA87",
                        easting = "${"%.3f".format(result.publishedE)} m",
                        northing = "${"%.3f".format(result.publishedN)} m",
                        height = result.publishedH?.let { "${"%.3f".format(it)} m" },
                        modifier = Modifier.fillMaxWidth(),
                    )

                    CoordinateBlock(
                        label = "MEASURED \u00B7 EGSA87",
                        easting = "${"%.3f".format(result.measuredE)} m",
                        northing = "${"%.3f".format(result.measuredN)} m",
                        height = result.measuredH?.let { "${"%.3f".format(it)} m" },
                        modifier = Modifier.fillMaxWidth(),
                        fixQuality = result.fixQuality,
                        sigmaH = result.horizontalAccuracy?.let { "\u03C3H ${"%.3f".format(it)} m" },
                    )
                }

                // Section 4 — Timestamp + sats footer
                Row(
                    Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically,
                ) {
                    Row(
                        horizontalArrangement = Arrangement.spacedBy(4.dp),
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Icon(
                            Icons.Outlined.AccessTime,
                            contentDescription = null,
                            modifier = Modifier.size(14.dp),
                            tint = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                        Text(
                            SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US)
                                .format(Date(result.timestamp)),
                            style = MaterialTheme.typography.labelSmall,
                            fontFamily = CoordinateFont,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                    }
                    Text(
                        "${result.numSatellites} sats",
                        style = MaterialTheme.typography.labelSmall,
                        fontFamily = CoordinateFont,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
            }
        },
        confirmButton = {
            TextButton(onClick = { onShare(result.toShareText()) }) {
                Text("Share")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Close")
            }
        },
    )
}

@Composable
private fun ResidualRow(label: String, value: Double) {
    Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
        Text(label, style = LabelOverline)
        Text(
            "${"%.3f".format(value)} m",
            style = MonoDelta,
            color = when {
                kotlin.math.abs(value) < 0.02 -> MaterialTheme.colorScheme.primary
                kotlin.math.abs(value) < 0.05 -> MaterialTheme.colorScheme.tertiary
                else -> MaterialTheme.colorScheme.error
            },
            fontWeight = FontWeight.W500,
        )
    }
}
